# dbuild configuration file

build:
  variants:
    - tag: latest
      containerfile: Containerfile
      default: true

cit:
  mode: screenshot
  port: 9191
  health: /
  wait: 180
  edge_threshold: 0.004
  annotations:
    - org.freebsd.jail.allow.sysvipc=true
